### ISSUE TITLE
add license information lookup

### ISSUE THREAD

**Issue by stevegoldsmith** [ad1217/Hacky_FDLog#6]
next to Log! button add Lookup which would pull name and address from qrz (might need to use their API to do volume lookups)

non api url is:
https://www.qrz.com/lookup/w1hs

their api is documented.

**Comment by ad1217** [comment]
Looks like that would need a QRZ subscription to do real API lookups: https://www.qrz.com/page/xml_data.html. If I wanted to use a single license, I could write a proxy that handled auth, I guess. I'd also have to write a UI, obviously, which has the advantage of being more nicely integrated, and the disadvantage of having to write/maintain it.

Without a license, I could stick their normal lookup pages in `iframe`s (or separate windows), or I could just make links to open in new tabs. This would just rely on users logging in locally to normal accounts.

**Comment by ad1217** [comment]
If you just want license information, including name and address, https://callook.info/w1hs would be an option. It has an open API which is quite straightforward. Also a JS library: https://www.npmjs.com/package/callook.

**Comment by stevegoldsmith** [comment]
yea, that’d be fine.


> On May 20, 2020, at 2:05 PM, Adam Goldsmith <notifications@github.com> wrote:
> 
> n


-- 
/steve
