### ISSUE TITLE
flag log entries with inconsistent exchange

### ISSUE THREAD

**Issue by stevegoldsmith** [ad1217/Hacky_FDLog#7]
Hilight log entry in red if we have worked a station more than once and the exchanges are not the same, indicates someone copied incorrectly.

Another option would be to pre-fill exchange based on previous log entry, but for FD might be better to encourage people to copy exchange correctly on their own.

**Comment by ad1217** [comment]
Implemented in 39a7d98fd644b1d7eb6cce54d477f9723ef7f4b1.
